version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:12.4-alpine
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    environment:
      PGUSER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    networks:
      - skymarket_network
    restart: always
    ports:
    - ${DB_PORT}:5432

  backend:
    container_name: back
    build:
      context: ../skymarket
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - skymarket_network
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - db
    command: bash -c 'python3 manage.py runserver ${WEB_HOST}:${WEB_PORT}'


  frontend:
    container_name: front
    build: ../frontend_react/.
    volumes:
      - ../frontend:/app/build
    networks:
      - skymarket_network
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - ${NGINX_PORT}:8001
      - ${FRONT_PORT}:3000
    volumes:
      - ../skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ../skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend:/usr/share/nginx/html/
    restart: always
    networks:
      - skymarket_network
    depends_on:
      - backend
      - frontend

networks:
  skymarket_network:
    driver: bridge

volumes:
  postgres_data:  
  frontend:
  nginx.conf:
  django_media:
  django_static:
